#!/usr/bin/env ruby

require 'rubygems'
require 'commander/import'
require 'rmusic'

program :version, '1.0'
program :description, 'A command line interface for RMusic'
 
command :chords do |c|
  c.syntax = 'rmusic chords [options]'
  c.summary = ''
  c.description = ''
  c.example 'Asus4 C# Dmin', 'Finds this sequence of chords'
  c.option '--capo FRET', Integer, 'Positions a capo'
  c.option '--open', 'Prefer open chords'
  c.action do |args, options|
    g = Rmusic::StringedInstrument.guitar()
  
    args.each { |arg|
      Rmusic::ChordCache.find( g, arg ).each { |c|
        print "#{arg}\n#{c.pretty}\n\n"
        break
      }
    }
  end
end

command :buildcache do |c|
  c.syntax = 'rmusic buildcache'
  c.action do |args, options|
    g = Rmusic::StringedInstrument.guitar()
    12.times { |n|
      Rmusic::ChordLibrary::CHORDS.each { |c|
        print "#{c.name}\n"
        Rmusic::ChordCache.find_chord( g, c, n )
      }
    }
  end
end
